# Setup
title:               'Tyler Grunenwald'
tagline:             'Programmer'
description: >-       
  Software developer in the greater Minneapolis-St. Paul area.
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty
excerpt_separator:   <!--more-->

  #linkedin_username: tylergrunenwald
  #github_username:  tdgrunenwald

# About/contact
author:
  name:              Tyler Grunenwald
  url:               https://linkedin.com/in/tylergrunenwald
  email:             tylergrunenwald@gmail.com

# Build settings
destination: ../docs # location served by GH pages

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
